# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10
  - name: 生活常识
    url: docs/
    weight: 20
  - name: 科研杂记
    url: blog/
    weight: 30
  - name: 文学
    url: showcase/
    weight: 40
  - name: 教程
    url: community/
    weight: 50
